@startuml

autonumber

ECA -> ECA: Lookup Plugin

loop till the end
ECA -> NTT: Get Reflection Information
NTT --> ECA: Reflection Information
ECA -> ECA:  initialize reverse-proxy
end

group ECA call
Client -> ECA: get api/core/v1alpha37/customers
ECA --> Client: get api/core/v1alpha37/customers  response
end

group NTT Super API call
Client -> ECA: get api/ntt/v2022.2.0/superAPI request
ECA -> NTT: proxy api/ntt/v2022.2.0/superAPI request
NTT --> ECA: api/ntt/v2022.2.0/superAPI response
ECA --> Client: proxy api/ntt/v2022.2.0/superAPI response
end

@enduml