@startuml

autonumber

Server -> Plugin: Start Process, read stdout
Plugin --> Server: Write unix socket on which gRPC server started

loop till the end
Plugin -> Server: Logs via gRPC
end

Server -> Plugin: Request
Plugin --> Server: Response


Server -> Plugin: Close
Plugin --> Plugin: os.Exit

@enduml